---
title: Çünkü 'Catch' bloğuna erişilemedi '&lt;name1&gt;'devralınan'&lt;name2&gt;'
ms.date: 07/20/2015
f1_keywords:
- BC42029
- vbc42029
helpviewer_keywords:
- BC42029
ms.assetid: 4bc84a84-ec7e-49db-8794-4fb71d36d5c0
ms.openlocfilehash: 7a51857bf2f181224c64a4295001e5ea24474cdb
ms.sourcegitcommit: 0888d7b24f475c346a3f444de8d83ec1ca7cd234
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 12/22/2018
ms.locfileid: "53767484"
---
# <a name="catch-block-never-reached-because-ltname1gt-inherits-from-ltname2gt"></a>Çünkü 'Catch' bloğuna erişilemedi '&lt;name1&gt;'devralınan'&lt;name2&gt;'
A `Catch` blok kod içinde hiç ulaşılamadı.  
  
 Varsayılan olarak, bu iletiyi bir uyarıdır. Uyarıları gizleme veya uyarıları hata olarak değerlendirmesini daha fazla bilgi için bkz: [Visual Basic'teki uyarıları yapılandırma](/visualstudio/ide/configuring-warnings-in-visual-basic).  
  
 **Hata Kimliği:** BC42029  
  
## <a name="to-correct-this-error"></a>Bu hatayı düzeltmek için  
  
-   Fazla `Catch` blok.  
  
## <a name="see-also"></a>Ayrıca Bkz.  
 [Nasıl yapılır: Bir Try koduyla test... Visual Basic'te catch bloğu](https://msdn.microsoft.com/library/8368e205-ed73-4185-a247-af84fb4fafa9)  
 [Try...Catch...Finally Deyimi](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
